<?php
// debug_login.php
require 'api/db.php';

// Введите сюда email, под которым не можете войти
$test_email = 'domchynskyi@ukr.net'; // <--- ЗАМЕНИТЕ НА ВАШ EMAIL
$test_pass  = '11223344';          // <--- ЗАМЕНИТЕ НА ВАШ ПАРОЛЬ

echo "<h3>Login Debugger</h3>";

try {
    // 1. Ищем пользователя
    $stmt = $pdo->prepare("SELECT * FROM users WHERE email = ? OR username = ?");
    $stmt->execute([$test_email, $test_email]);
    $user = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$user) {
        die("<div style='color:red'>User not found! Check email spelling.</div>");
    }

    echo "User found: <strong>" . htmlspecialchars($user['username']) . "</strong><br>";
    echo "ID: " . $user['id'] . "<br><br>";

    // 2. Проверяем колонки с паролем
    $pass_col = isset($user['password']) ? 'password' : 'NONE';
    $hash_col = isset($user['password_hash']) ? 'password_hash' : 'NONE';

    echo "Column 'password': " . ($pass_col !== 'NONE' ? "EXISTS" : "MISSING") . "<br>";
    echo "Column 'password_hash': " . ($hash_col !== 'NONE' ? "EXISTS" : "MISSING") . "<br><br>";

    // 3. Смотрим, что внутри
    $val_pass = $user['password'] ?? '';
    $val_hash = $user['password_hash'] ?? '';

    echo "Value in 'password': " . htmlspecialchars(substr($val_pass, 0, 20)) . "... (Length: " . strlen($val_pass) . ")<br>";
    echo "Value in 'password_hash': " . htmlspecialchars(substr($val_hash, 0, 20)) . "... (Length: " . strlen($val_hash) . ")<br><br>";

    // 4. Проверяем длину (Самая частая ошибка!)
    if (strlen($val_hash) > 0 && strlen($val_hash) < 60) {
        echo "<h2 style='color:red'>CRITICAL ERROR: Hash is truncated!</h2>";
        echo "Your database column is too short. It must be VARCHAR(255).<br>";
        echo "Current length is only " . strlen($val_hash) . " chars.<br>";
    }

    // 5. Пробуем верифицировать
    $realHash = !empty($val_hash) ? $val_hash : $val_pass;

    if (empty($realHash)) {
         echo "<h2 style='color:red'>ERROR: No password hash found in DB.</h2>";
    } else {
        $check = password_verify($test_pass, $realHash);
        if ($check) {
             echo "<h2 style='color:green'>SUCCESS: Password matches!</h2>";
             echo "The problem is likely in api.php code logic.";
        } else {
             echo "<h2 style='color:red'>FAILURE: Password does NOT match.</h2>";
             echo "1. Did you enter the correct password in this script?<br>";
             echo "2. Was the hash truncated? (See above)<br>";
             echo "3. Was the hash generated by a different system (MD5/SHA1)?";
        }
    }

} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}
?>